### ISSUE TITLE
Reg: File upload using tGoogledrive component. Fixed.

### ISSUE THREAD

**Issue by pswati36** [jlolling/talendcomp_tGoogleDrive#1]
Hi,

First of all thanks for tGoogleDrive component. All functionalities are working as expected except Upload File.
While uploading file I am facing compilation issue localUploadFile cannot be resolved to a variable.
When I went ahead to Java code generated in Talend and see.. there is a line generated as below
java.io.File f = new java.io.File(localUploadFile);

but I see variable defined as String localFilePath = "";

Could you please help to get it rectified. I use latest 3.3 still facing same issue. Please let me know for any other details if required.

I fixed it by changing tGoogleDrive_begin.javajet.

Thanks
Swati P

**Comment by jlolling** [comment]
It could be. And it has mostly todo with the job design.
Could you please send me a screenshot of the job design?

**Comment by jlolling** [comment]
If you have fixed the issue, would you please consider to create a pull request or send me your changes?
